Fail faster in `checkTokens`
microsoft/ado-npm-auth pull request #17
Opened 2024-04-22 14:18 UTC by jonchurch

Currently the code to check tokens will return `false` if any of the tokens we detect fail the network request.

But we are still doing sequential network calls to check that. 

This PR goes full fail fast via `Promise.all` and returns false if we reject

Is it faster? For most people, prolly not  `¯\_(ツ)_/¯` but if a user has several tokens (like I do) but only the last of 10 is bad, it should give us a faster result.

2024-04-22 17:30 UTC, jonchurch commented
I stand by this change, but interestingly we may also be able to parse the token to check its expiry, so we can fail even faster w/o a network request.

2024-04-22 17:52 UTC, jcreamer898 approved these changes

2024-04-22 20:06 UTC, jcreamer898 requested changes

2024-04-22 20:06 UTC, jcreamer898 commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +    ))
nit, missing `;` 🤣

2024-04-22 20:06 UTC, jcreamer898 commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +      })
might just wanna run `npm exec prettier --write src/**/*.ts` because I think there's a missing comma here too.

2024-04-22 21:59 UTC, jonchurch commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +      })
yar will do, didn't see a lint script in the repo

2024-04-22 22:02 UTC, jonchurch commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +      })
this creates a huge diff on whitespace mostly it looks like, in files I didn't touch yet

2024-04-22 22:08 UTC, jonchurch commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +      })
Fixed manually

2024-04-22 22:08 UTC, jonchurch commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +    ))
Fixed manually

2024-04-22 22:09 UTC, jonchurch commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +export const checkTokens = async function ({ feeds }: { feeds: NpmrcOrg[] }): Promise<boolean> {
slipped in an explicit return type here, which I prefer when things are this simple. It's really easy to mess this up and not realize bc no one checks the actual type, just does truthy/falsey compares on it.

2024-04-25 19:27 UTC, jonchurch commented on packages/ado-npm-auth/src/npmrc/check-tokens.ts
> +      })
If you're talking about L:28, a semi there breaks the code because you can't include semis in function args

2024-04-25 19:28 UTC, jonchurch commented
Requested changes have been made

2024-09-13 23:10 UTC, jonchurch commented
underlying file was deleted, logic is largely the same but closing since I don't plan to update this PR

2024-09-13 23:10 UTC, closed without merging